import { getPayload } from 'payload'
import configPromise from '../payload.config'
import path from 'path'
import { fileURLToPath } from 'url'
import fs from 'fs'
import sharp from 'sharp'

const filename = fileURLToPath(import.meta.url)
const dirname = path.dirname(filename)

async function testSharp() {
  console.log('--- SHARP FUNCTIONAL TEST START ---')
  console.log('Initializing Payload...')
  const payload = await getPayload({ config: configPromise })

  const tempDir = path.resolve(dirname, '../../scratch')
  if (!fs.existsSync(tempDir)) {
    fs.mkdirSync(tempDir, { recursive: true })
  }
  const testImagePath = path.resolve(tempDir, 'sharp-test-source.png')

  // Generate a valid 1920x1080 high-res image using Sharp
  console.log('Creating high-res 1920x1080 source image...')
  await sharp({
    create: {
      width: 1920,
      height: 1080,
      channels: 4,
      background: { r: 245, g: 158, b: 11, alpha: 1 }, // Yellow gold
    },
  })
    .png()
    .toFile(testImagePath)

  const buffer = fs.readFileSync(testImagePath)
  const stats = fs.statSync(testImagePath)

  console.log(`Source image created: ${testImagePath} (${stats.size} bytes)`)

  // Upload through Payload CMS
  console.log('Uploading test image via Payload Media collection...')
  const media = await payload.create({
    collection: 'media',
    data: {
      alt: 'Payload Sharp Functional Test Image',
      caption: '1920x1080 source image testing mobile/tablet/desktop variants',
    },
    file: {
      data: buffer,
      mimetype: 'image/png',
      name: `sharp-test-${Date.now()}.png`,
      size: stats.size,
    },
  })

  console.log('Upload successful! Media Document ID:', media.id)
  console.log('Media filename:', media.filename)
  console.log('Sizes generated by Sharp:');
  const sizes = (media as any).sizes || {}
  for (const [key, val] of Object.entries(sizes)) {
    const s = val as any
    console.log(`  - Variant [${key}]: ${s.filename || 'N/A'} (width: ${s.width}px, height: ${s.height}px, size: ${s.filesize} bytes)`)
  }

  const generatedKeys = Object.keys(sizes)
  const hasMobile = generatedKeys.includes('mobile')
  const hasTablet = generatedKeys.includes('tablet')
  const hasDesktop = generatedKeys.includes('desktop')

  if (hasMobile && hasTablet && hasDesktop) {
    console.log('✅ Sharp verification SUCCESSFUL: mobile (480w), tablet (768w), and desktop (1280w) variants generated!')
  } else {
    console.error('❌ Sharp verification INCOMPLETE: Missing expected responsive variants', generatedKeys)
  }

  console.log('--- SHARP FUNCTIONAL TEST FINISHED ---')
  process.exit(0)
}

testSharp().catch((err) => {
  console.error('Sharp test failed with error:', err)
  process.exit(1)
})
